# Generated by Django 3.0.6 on 2020-06-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='image',
            field=models.ImageField(default='null', upload_to='Proyects'),
        ),
    ]
