# Generated by Django 3.0.6 on 2020-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('proyectos', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='usersPatrons',
            field=models.ManyToManyField(default='null', to='usuarios.User', verbose_name='Patrons'),
        ),
    ]
