# Generated by Django 3.0.6 on 2020-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20200606_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='deadline',
            field=models.CharField(max_length=50),
        ),
    ]
