# Generated by Django 3.0.6 on 2020-06-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('proyectos', '0006_auto_20200607_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='usersPatrons',
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.User', verbose_name='Patron')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyect', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyect',
            name='Patrons',
            field=models.ManyToManyField(default='null', through='proyectos.Patron', to='usuarios.User', verbose_name='Patrons'),
        ),
    ]
