# Generated by Django 3.0.6 on 2020-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20200607_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
