# Generated by Django 3.0.6 on 2020-06-27 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_patron_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 18, 5, 22, 901226)),
        ),
    ]
