# Generated by Django 3.0.6 on 2020-06-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('name', models.EmailField(max_length=254)),
                ('password', models.BinaryField(unique=True)),
                ('made', models.DateTimeField(auto_now_add=True)),
                ('upload', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='null', upload_to='users')),
                ('wallet', models.FloatField()),
            ],
        ),
    ]
