# Generated by Django 3.0.6 on 2020-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200605_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
